version: '3.10.11'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - redis
    env_file:
      - .env
    container_name: richai-gpt

  redis:
    image: "redis:alpine"
    ports:
      - "0.0.0.0:6379:6379"
    volumes:
      - redis-data:/data


volumes:
  redis-data:
